---
title: "GO enrichment analysis"
output: html_document
date: "2024-04-11"
---


```{r, echo=F, warning=F, message=F}
rm(list=ls())
set.seed(123)
knitr::opts_chunk$set(autodep = TRUE)
library(knitr)
library(RSQLite)
library(ggplot2)
library(dplyr)
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE) # avoid error of long vectors https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script 
library(kableExtra)
library(RColorBrewer)
library(gplots)
library(tidyverse)
library(gridExtra)
library(ggpubr)
library(DT)
#library("devtools")
#install.packages("Rtools")
#install_github('xinhe-lab/mirage')
library(mirage)

multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}

pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<1e-10)
    p_value_adjust[i]="<1e-10"
  if (is.na(p_value[i])==F & p_value[i]>1e-10)
    p_value_adjust[i]=round(p_value[i],10)
}
  return(p_value_adjust)
}

```



```{r, echo=F, message=F, warning=F}
GO=c("membrane depolarization during cardiac muscle cell action potential(GO:0086012)", "mechanosensory behavior (GO:0007638)", "membrane depolarization during action potential (GO:0086010)", "cell-cell signaling involved in cardiac conduction (GO:0086019)", "regulation of heart rate by cardiac conduction (GO:0086091)", "regulation of cell size (GO:0008361)", "neuron projection morphogenesis (GO:0048812)", "plasma membrane bounded cell projection morphogenesis (GO:0120039)", "cell projection morphogenesis (GO:0048858)", "cell part morphogenesis (GO:0032990)")
go_enrichment_biological_process=data.frame(fold_change=c(53.13,51.61, 47.53,33.45, 22.03, 0, 0, 0, 0, 0, 0, 64.65, 0, 0, 0, 9.28, 5.38,5.32, 5.27, 5.08), pvalue=c(1.05E-03
,2.33E-02
,1.68E-03
,7.66E-03
,4.91E-02
,rep(1,5), 1, 9.40E-03
,  1,1,1, 2.92E-02
,2.53E-02
,2.79E-02
,3.08E-02
,4.50E-02
), GO_term=rep(GO,2), Gene_set=rep(c("MIRAGE FDR genes", "MIRAGE new genes"), each=length(GO)))



ggplot(go_enrichment_biological_process, aes(x = GO_term, y = fold_change, fill = Gene_set)) + 
  geom_col(position = 'dodge', width = 0.8, 
           aes(color = after_scale(colorspace::darken(fill, 1.3)))) + 
#  geom_text(aes(label = paste("p", scales::pvalue(pvalue)), group = Gene_set),
 #           vjust = -1, position = position_dodge(width = 0.8)) +
  labs(x = "", y = "Fold change", fill = "Gene_set") + 
  scale_fill_manual(values = c("pink", "red")) +
  #scale_y_log10(expand = c(0.05, 0)) +
  theme_classic(base_size = 12) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=9))+
  theme(axis.text.y = element_text(angle = 0, vjust = 0.5, size=7.5))+
  theme(legend.position = "bottom")+
theme(legend.title=element_blank())+
  theme(legend.text=element_text(size=8))+
  ggtitle("GO biological process complete")+
coord_flip()



#ggplot(results, aes(x = breadth, y = enrichment, fill = ontology)) + 
#  geom_col(position = 'dodge', width = 0.8, 
#           aes(color = after_scale(colorspace::darken(fill, 1.3)))) + 
#  geom_text(aes(label = paste("p", scales::pvalue(p)), group = ontology),
#            vjust = -1, position = position_dodge(width = 0.8)) +
#  labs(x = "Breadth", y = "Odds ratio", fill = "Ontology") + 
#  scale_fill_manual(values = c("#d63228", "#dff2f8", "#4575b5")) +
#  scale_y_log10(expand = c(0.05, 0)) +
#  theme_classic(base_size = 16) +
#  theme(legend.position = "top")


```