---
title: "temporal gene expression"
output: html_document
date: "2024-01-10"
---


```{r, echo=F, message=F, warning=F}
rm(list=ls())
set.seed(123)
knitr::opts_chunk$set(autodep = TRUE)
library(knitr)
library(RSQLite)
library(dplyr)
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE) # avoid error of long vectors https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script 
library(kableExtra)
library(RColorBrewer)
library(gplots)
library(tidyverse)
library(gridExtra)
library(ggpubr)
library(DT)
#library("devtools")
#install.packages("Rtools")
#install_github('xinhe-lab/mirage')
library(mirage)

multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}

pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<1e-10)
    p_value_adjust[i]="<1e-10"
  if (is.na(p_value[i])==F & p_value[i]>1e-10)
    p_value_adjust[i]=round(p_value[i],10)
}
  return(p_value_adjust)
}

```



```{r, echo=F, message=F, warning=F, results=F}

######## replicating the results 
###https://github.com/linnykos/covarianceSelection
rm(list=ls())
set.seed(123)

# install dependent packages 

#install.packages("doMC", repos="http://R-Forge.R-project.org")
library("doMC")

# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("org.Hs.eg.db")
library("org.Hs.eg.db")

#download gz file to local folder and install https://cran.r-project.org/src/contrib/Archive/dequer/
library(dequer)
library(dplyr)

library("devtools")
devtools::install_github("linnylin92/covarianceSelection", subdir = "covarianceSelection")

```



```{r, echo=F, message=F, warning=F, eval=T, results=F}
# step0_loading.R  https://github.com/linnykos/covarianceSelection/blob/master/main/step0_loading.R
# step0_loading.R loads the BrainSpan dataset and TADA dataset (i.e., matching the genes in both datasets, resolving gene synonyms, removing genes not expressed in the brain).

#if(verbose) print("Start of step 0: Loading")

#format the brainspan dataset
#load("../../raw_data/newGenexp.RData")
load("C:/han/Dataset/20231006_PMID_33731968/NIHMS1598069-supplement-Supp_1/newGenexp.RData")
rownames(genexp) <- genexp[,1]
genexp <- genexp[,-1]
genexp <- t(genexp)
genexp <- as.data.frame(genexp) # 1340 x 16947 ? what does row names indicate? 

#determine brain-expressed genes
brain_expression <- covarianceSelection::brain_expression # how these genes are known to be expressed genes????????  
brain_genes <- brain_expression$Gene[brain_expression$Brain_expressed != 'No']
idx <- which(colnames(genexp) %in% brain_genes)
genexp <- genexp[,idx] # 1340 x 14370

############ sample information is in covarianceSelection::brainspan_id


#translate into synonyms
vec <- covarianceSelection::symbol_synonyms(colnames(genexp), verbose = T)
unknown_genes_idx <- which(is.na(vec))
vec <- vec[-unknown_genes_idx]
genexp <- genexp[-unknown_genes_idx] # 1340 x 14297
colnames(genexp) <- vec

#average non-unique genes
genexp <- covarianceSelection:::average_same_columns(genexp) # 1340 x 14246

#remove samples from subregions that we don't have a region for
region_subregion <- covarianceSelection::region_subregion
vec <- rownames(genexp)
subregion <- unlist(strsplit(vec,"\\."))[seq(2, length(vec)*4, 4)]
idx <- which(subregion %in% region_subregion$subregion)
genexp <- genexp[idx,] # 1294 x 14249

################
# explore the notations in row names 
#sample_names=rownames(genexp)
#comma_position=gregexpr(".", sample_names[1])
#sample_names[grepl("VFC",sample_names)] # find samples having "VFC"
################
```



## temporal gene expression 

```{r, echo=F, message=F, warning=F, eval=T}

##############
##########
rm("BF.PP.gene")
#BF.PP.gene=as_tibble(read.csv("C:\\han\\Dataset\\SCHEMA\\MIRAGE_on_meta_sample_estimate_delta_3vargroups_20231027.csv", header=T))
load("C:\\han\\Dataset\\SCHEMA\\MIRAGE_on_meta_sample_estimate_delta_2vargroups_for_constraint_gene_20231120.RData")

fdr_function=function(fdr_threshold, data)
{
tau=seq(0, 0.999, by=0.001)
num_pred=NULL
false_disc=NULL
FDR=NULL
for (i in 1:length(tau))
{
num_pred[i]=sum(ifelse(data$post_prob>tau[i], 1, 0))
false_disc[i]=sum((1-data$post_prob)*ifelse(data$post_prob>tau[i], 1, 0))
FDR[i]=false_disc[i]/num_pred[i]
}
tau_fdr=tibble(tau=tau, fdr=FDR)%>%drop_na()  # drop rows with NA
tau_at_threshold=tau_fdr%>%filter(fdr<=fdr_threshold)
if (nrow(tau_at_threshold)==0)
  return("No gene is selected")
if (nrow(tau_at_threshold)>0)
{
  tau_threshold=tau_at_threshold$tau[1]
  return(data%>% filter(post_prob>tau_threshold))
}

}
```

```{r, echo=T, message=F, warning=F, eval=T}
input_data=BF.PP.gene
colnames(input_data)[3]="post_prob"
FDR_gene=fdr_function(fdr_threshold = 0.05, input_data)
```


```{r, echo=F, message=F, warning=F}
Braincode_stage1=covarianceSelection::brainspan_id$Braincode[1:4] #4-10 PCW
Braincode_stage2=covarianceSelection::brainspan_id$Braincode[5:16] #10-19 PCW
Braincode_stage3=covarianceSelection::brainspan_id$Braincode[17:28] #19PCW-6 months
Braincode_stage4=covarianceSelection::brainspan_id$Braincode[29:57] #6 months-onwards 
FDR_gene_expression=numeric()

FDR_gene_col_index=which(colnames(genexp)%in%FDR_gene$Gene)
stage_row_index=numeric()
for (i in 1:length(Braincode_stage1))
  stage_row_index=c(stage_row_index, rownames(genexp)[grepl(Braincode_stage1[i], rownames(genexp))])
FDR_gene_stage1=genexp[which(rownames(genexp)%in%stage_row_index), c(FDR_gene_col_index)]
FDR_gene_expression[1]=sum(FDR_gene_stage1)

stage_row_index=numeric()
for (i in 1:length(Braincode_stage2))
  stage_row_index=c(stage_row_index, rownames(genexp)[grepl(Braincode_stage2[i], rownames(genexp))])
FDR_gene_stage2=genexp[which(rownames(genexp)%in%stage_row_index), c(FDR_gene_col_index)]
FDR_gene_expression[2]=sum(FDR_gene_stage2)

stage_row_index=numeric()
for (i in 1:length(Braincode_stage3))
  stage_row_index=c(stage_row_index, rownames(genexp)[grepl(Braincode_stage3[i], rownames(genexp))])
FDR_gene_stage3=genexp[which(rownames(genexp)%in%stage_row_index), c(FDR_gene_col_index)]
FDR_gene_expression[3]=sum(FDR_gene_stage3)

stage_row_index=numeric()
for (i in 1:length(Braincode_stage4))
  stage_row_index=c(stage_row_index, rownames(genexp)[grepl(Braincode_stage4[i], rownames(genexp))])
FDR_gene_stage4=genexp[which(rownames(genexp)%in%stage_row_index), c(FDR_gene_col_index)]
FDR_gene_expression[4]=sum(FDR_gene_stage4)

 FDR_gene_expression_normalize=(FDR_gene_expression-mean(FDR_gene_expression))/sd(FDR_gene_expression)
 
 ggplot(data.frame(gene_expression=FDR_gene_expression_normalize, stage=c("4-10 PCW", "10-19 PCW", "19 PCW-6 months", "6 months-onward")), aes(x=stage, y=gene_expression, group=1)) +
  geom_line()+
  geom_point()  # normalize gene expression 
 
 
  ggplot(data.frame(gene_expression=FDR_gene_expression/length(FDR_gene_col_index), stage=c("4-10 PCW", "10-19 PCW", "19 PCW-6 months", "6 months-onward")), aes(x=stage, y=gene_expression, group=1)) +
  geom_line()+
  geom_point()   # average gene expression per gene 
  
  
  ggplot(data.frame(gene_expression=FDR_gene_expression/c(prod(dim(FDR_gene_stage1)), prod(dim(FDR_gene_stage2)), prod(dim(FDR_gene_stage3)), prod(dim(FDR_gene_stage4))), stage=c("4-10 PCW", "10-19 PCW", "19 PCW-6 months", "6 months-onward")), aes(x=stage, y=gene_expression, group=1)) +
  geom_line()+
  geom_point()   # average gene expression per gene per region 
 
```